apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    appname: busybox_app3
  name: busybox-pvc-41-clone
spec:
  accessModes:
  - ReadWriteOnce
  dataSource:
    apiGroup: ""
    kind: PersistentVolumeClaim
    name: busybox-pvc-41
  dataSourceRef:
    apiGroup: ""
    kind: PersistentVolumeClaim
    name: busybox-pvc-41
  resources:
    requests:
      storage: 42Gi
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem
