apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    appname: busybox_app3
  name: busybox-pvc-41
spec:
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    name: busybox-pvc-41-snapshot
    kind: VolumeSnapshot
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 42Gi
  storageClassName: ocs-storagecluster-ceph-rbd
