---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: rdr/busybox/cephfs/workloads/app-busybox-3
  labels:
    app: busybox-sample
  name: busybox-sub
spec:
    channel: ramen-busybox-3/ramen-gitops
    placement:
      placementRef:
        kind: Placement
        name: busybox-placement
