---
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: multi-busybox-drpc-2
  labels:
    app: multi-busybox-sample
spec:
  preferredCluster: "amagrawa-c1-9jan"
  drPolicyRef:
    name: my-drpolicy-5
  placementRef:
    kind: PlacementRule
    name: multi-sub-busybox-placement-2
  pvcSelector:
    matchLabels:
      appname: busybox_app2
