---
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: multi-busybox-drpc-1
  labels:
    app: multi-busybox-sample
spec:
  preferredCluster: "amagrawa-c1"
  drPolicyRef:
    name: my-drpolicy-30
  placementRef:
    kind: PlacementRule
    name: multi-sub-busybox-placement-1
  pvcSelector:
    matchLabels:
      appname: busybox_app1
