---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vm-1-pvc-clone
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
  storageClassName: ocs-storagecluster-ceph-rbd-virtualization
  volumeMode: Block
