resources:
- ../../../base
patches:
  - target:
      kind: Deployment
      labelSelector: workloadpattern=simple_io
    patch: |-
      - op: replace
        path: /metadata/labels/appname
        value: busybox_app_2
  - target:
      kind: PersistentVolumeClaim
      labelSelector: appname=busybox_app1
    patch: |-
      - op: replace
        path: /metadata/labels/appname
        value: busybox_app2